trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build the app bbnb'

- script: dotnet test
  displayName: 'Tests CK'

- task: CopyFiles@2
  inputs:
    contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional (0b71cbad-e0a9-4f4d-8fe2-e887c7702cc0)'
    appType: 'webApp'
    WebAppName: 'ConnectivityApp'
    deployToSlotOrASE: true
    ResourceGroupName: 'connectivity_ck'
    SlotName: 'production'
    VirtualApplication: 'ConnectivityApp'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    TakeAppOfflineFlag: false
    RemoveAdditionalFilesFlag: true
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core