trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Connectivity.Web'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet publish $(projectName) --configuration $(Build.SourceBranchName)
  displayName: 'Build and publish the app for $(Build.SourceBranchName) ck'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts to drop/$(Build.SourceBranchName)'
  inputs:
    PathtoPublish: '$(projectName)/bin/Release/netcoreapp3.0/publish'
    ArtifactName: 'drop/$(Build.SourceBranchName)'
    publishLocation: 'Container'