trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Connectivity.Web'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    targetConfiguration: 'Production'
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    targetConfiguration: 'Staging'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet publish $(projectName) --configuration $(targetConfiguration)
  displayName: 'Build and publish $(projectName) as $(targetConfiguration) for $(Build.SourceBranchName)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts to drop/$(targetConfiguration)'
  inputs:
    PathtoPublish: '$(projectName)/bin/$(targetConfiguration)/netcoreapp3.0/publish'
    ArtifactName: 'drop/$(targetConfiguration)'
    publishLocation: 'Container'