trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet publish Connectivity.Web --configuration $(buildConfiguration)
  displayName: 'Build and publish the app bbnb'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Connectivity.Web/bin/Release/netcoreapp3.0/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'