trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Connectivity.WebApi'
  isMasterBranch: $[eq(variables['Build.SourceBranchName'], 'master')]
  targetConfiguration: $[if(variables.isMasterBranch, 'Production', 'Staging')]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet publish $(projectName) --configuration $(targetConfiguration)
  displayName: 'Build and publish $(projectName) as $(targetConfiguration) for $(Build.SourceBranchName)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts to drop/$(Build.SourceBranchName)'
  inputs:
    PathtoPublish: '$(projectName)/bin/$(Build.SourceBranchName)/netcoreapp3.0/publish'
    ArtifactName: 'drop/$(Build.SourceBranchName)'
    publishLocation: 'Container'