trigger:
- master|dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet publish Connectivity.WebApi --configuration $(buildConfiguration)
  displayName: 'Build and publish the api $(Build.SourceBranchName)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Connectivity.WebApi/bin/Release/netcoreapp3.0/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'